# Generated by Django 2.0.3 on 2018-03-20 05:48

from django.db import migrations, models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('twyla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(max_length=17, unique=True, validators=[project.validators.ISBNValidator]),
        ),
    ]
