# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-03 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
        migrations.DeleteModel(
            name='MyUUIDModel2',
        ),
    ]
