# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20180303_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_you',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_position',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
