# Generated by Django 2.0.3 on 2018-03-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'permissions': (('read_name_article', "Read article's name"), ('change_name_article', "Change article's name"), ('read_author_article', "Read article's author"), ('change_author_article', "Change article's author")),
            },
        ),
    ]
