# Generated by Django 2.0.3 on 2018-03-11 06:32

from django.db import migrations
from project.apps.motius.models import Article
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

def create_article_field_permissions(apps, schema_editor):
    content_type = ContentType.objects.get_for_model(Article)
    # read
    permission = Permission.objects.create(
        codename='read_name_article',
        name="Read article's name",
        content_type=content_type,
    )
    # change
    permission = Permission.objects.create(
        codename='change_name_article',
        name="Change article's name",
        content_type=content_type,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('motius', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_article_field_permissions),
    ]
