# Generated by Django 2.0.3 on 2018-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motius', '0002_auto_20180311_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
