# Generated by Django 2.0.3 on 2018-03-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motius', '0003_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('read_name_article', "Read article's name"), ('change_name_article', "Change article's name"), ('read_author_article', "Read article's author"), ('change_author_article', "Change article's author"))},
        ),
    ]
